const List<Map<String, dynamic>> DOC_LIST_DATA = [
  {
    "id": 1,
    "name": "Alice",
    "address": "28 Winchester St.Valrico, FL 33594",
    "speciality": "NUROLOGIST",
    "imageUrl":
        "http://wwsthemes.com/themes/medwise/v1.3/images/doctor-single.jpg",
    "experience": 5,
    "rating": 4.5,
    "price": 350,
  },
  {
    "id":2,
    "name": "Matt",
    "address": "837 Sherman Avenue Perrysburg, OH 43551",
    "speciality": "NUROLOGIST",
    "imageUrl":"http://medcare-demo.detheme.com/video/wp-content/uploads/sites/6/2016/02/doctor-profile03.jpg",
    "experience": 3,
    "rating": 4.5,
    "price": 500,
  },
  {
    "id": 3,
    "name": "Janet",
    "address": "9437 S. Oak Meadow Ave. Pleasanton, CA 94566",
    "speciality": "PROCTOLOGIST",
    "imageUrl":
        "http://s7606.pcdn.co/wp-content/uploads/2016/07/Dr.-Naila-Alam.jpg",
    "experience": 5,
    "rating": 4.5,
    "price": 350,
  },
  {
    "id": 4,
    "name": "Robert",
    "address": "02 S. Westminster St.Bethesda, MD 20814",
    "speciality": "NUROLOGIST",
    "imageUrl": "https://www.browardhealth.org/-/media/BH_Doctor_Images/108634.png",
    "experience": 15,
    "rating": 4.5,
    "price": 350,
  },
  {
    "id": 5,
    "name": "Harvinder Singh",
    "address": "552 Proctor Dr.Harvinder, MD 20601",
    "speciality": "General Physician",
    "imageUrl":"https://shrimannhospitals.com/uploads/1558072620-drjssaini.jpg",
    "experience": 25,
    "rating": 4.5,
    "price": 350,
  },
];
